# Logging configuration. Valid options are: LOG_ERROR, LOG_WARNING, LOG_INFO, LOG_DEBUG, LOG_TRACE
logLevel: LOG_ERROR

# Hostname of the coordinator. Passed to the internal worker, so it can connect over the local network.
# Corresponds to the service name in docker-compose.yml.
coordinatorHost: 10.1.1.1

#rpcPort: 1200
#restPort: 8081

# Hostname under which the internal worker registers with the coordinator.
# Corresponds to the service name in docker-compose.yml.
worker:
  localWorkerHost: 10.1.1.1

# IP address of the coordinator REST API. 0.0.0.0 is reachable from outside the Docker container.
restIp: 0.0.0.0

# Configure logical sources.
# - logicalSourceName: Each logical source is identified by a unique name.
# - fields: A source has a schema, an unordered list of named and typed attributes.
# Valid types are:
# - INT8, INT16, INT32, INT64
# - UINT8, UINT16, UINT32, UINT64
# - FLOAT32, FLOAT64
# - BOOLEAN
# - TEXT
logicalSources:
  - logicalSourceName: bid
    fields:
      - name: auctionId
        type: INT64
      - name: cart
        type: INT32
      - name: cort
        type: INT32
      - name: curt
        type: INT32
      - name: price
        type: FLOAT64
      - name: timestamp
        type: UINT64

  - logicalSourceName: auction
    fields:
      - name: id
        type: INT64
      - name: line
        type: INT64
      - name: itemName
        type: TEXT
      - name: description
        type: TEXT
      - name: initialbid
        type: INT32
      - name: reserve
        type: INT32
      - name: expires
        type: INT32
      - name: seller
        type: INT32
      - name: category
        type: INT32
      - name: timestamp
        type: UINT64

#  - logicalSourceName: tcpsourcee
#    fields:
#      - name: id
#        type: INT64
#      - name: value
#        type: INT32

# Enable merging of operators from multiple queries in the global query plan.
# - DefaultQueryMergerRule: No query merging
# - HashSignatureBasedPartialQueryMergerRule: Syntactic query merging
# - Z3SignatureBasedCompleteQueryMergerRule: Semantic query merging
optimizer:
  queryMergerRule: "DefaultQueryMergerRule"


