status = error
name = FlinkRootLogger
property.file.separator = /
property.key.separator = =
property.line.separator = \n
appender.console.type = Console
appender.console.name = ConsoleAppender
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{HH:mm:ss,SSS} %-5p [%t] %c{1} - %m%n

rootLogger.level = INFO
rootLogger.appenderRefs = stdout
rootLogger.appenderRef.stdout.ref = ConsoleAppender

